version: "3.8"

x-env-db: &env_db
  POSTGRES_USER: hacker_user
  POSTGRES_PASSWORD: hacker_pass
  POSTGRES_DB: hacker_db

services:
  postgres:
    image: postgres:alpine
    environment:
      <<: *env_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - hacker

  app:
    build:
      context: .
    image: my_registry/hacker_app
    environment:
      <<: *env_db
      RAILS_ENV: development
      POSTGRES_HOST: postgres
      SECRET_KEY: 3bbd1b066a2349e51f198736788ca87e
    command: >
      sh -c "
        bundle install;
        sleep 15;
        bundle exec rails db:migrate;
        bundle exec rails db:seed;
        rm -rf ./tmp;
        bundle exec rails s -b 0.0.0.0 -p 3000;
      "
    ports:
      - "3000:3000"
    volumes:
      - .:/opt/app
    depends_on:
      - postgres
    networks:
      - hacker

  redis:
    image: redis
    command: redis-server
    networks:
      - hacker

  sidekiq:
    image: my_registry/hacker_app
    environment:
      <<: *env_db
      RAILS_ENV: development
      POSTGRES_HOST: postgres
      SECRET_KEY: 3bbd1b066a2349e51f198736788ca87e
      REDIS_URL: redis://redis:6379
    command: >
      sh -c "
        bundle install;
        bundle exec sidekiq;
      "
    volumes:
      - .:/opt/app
    depends_on:
      - app
      - redis
    networks:
      - hacker

volumes:
  postgres-data:

networks:
  hacker:
